<?php
// Automatically Generated by TestLink Installer - Sun, 28 Oct 18 14:14:58 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink2');
define('DB_PASS', 'Inpecman1');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink2');
define('DB_TABLE_PREFIX', '');
